version: '3'
services:

  # Nginx
  react-nginx:
    image: nginx:alpine
    container_name: react-nginx
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_TAGS: docker
      SERVICE_NAME: nginx
    ports:
      - "${LISTEN_IP}:80:80"
    depends_on:
      - react-frontend
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    networks:
      - react-network

  # React-cli with frontend
  react-frontend:
    container_name: react-frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - "./:/app"
      - "/app/node_modules"
    environment:
      SERVICE_NAME: frontend
      SERVICE_TAGS: docker
      NODE_ENV: development
    networks:
      - react-network

# networks
networks:
  react-network:
    name: react-network
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "${LISTEN_IP}"
